package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/lucasaarch/terraform-provider-dokploy/internal/client"
)

const (
	defaultDeployTimeout = 10 * time.Minute
	deployPollInterval   = 5 * time.Second
)

var (
	_ resource.Resource                = &applicationResource{}
	_ resource.ResourceWithConfigure   = &applicationResource{}
	_ resource.ResourceWithImportState = &applicationResource{}
)

type applicationResource struct {
	client *client.Client
}

func NewApplicationResource() resource.Resource {
	return &applicationResource{}
}

type applicationModel struct {
	ID               types.String   `tfsdk:"id"`
	EnvironmentID    types.String   `tfsdk:"environment_id"`
	Name             types.String   `tfsdk:"name"`
	Description      types.String   `tfsdk:"description"`
	DockerImage      types.String   `tfsdk:"docker_image"`
	RegistryURL      types.String   `tfsdk:"registry_url"`
	RegistryUsername types.String   `tfsdk:"registry_username"`
	RegistryPassword types.String   `tfsdk:"registry_password"`
	Env              types.Map      `tfsdk:"env"`
	AppName          types.String   `tfsdk:"app_name"`
	Status           types.String   `tfsdk:"status"`
	Timeouts         timeouts.Value `tfsdk:"timeouts"`
}

func (r *applicationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application"
}

func (r *applicationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "A Dokploy application sourced from a Docker image. Applying this resource deploys the application and waits for it to finish.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"environment_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Environment the application belongs to. Changing this forces replacement.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Application name.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Application description. Note: once set, removing this attribute from the configuration does not clear the description on the server (the API silently keeps the existing value).",
			},
			"docker_image": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Docker image to deploy, e.g. `nginx:1.27`.",
			},
			"registry_url": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Private registry URL. Omit for public images.",
			},
			"registry_username": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				MarkdownDescription: "Registry username.",
			},
			"registry_password": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				MarkdownDescription: "Registry password. Not returned by the API; drift on this field is not detected.",
			},
			"env": schema.MapAttribute{
				Optional:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "Application environment variables.",
			},
			"app_name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Internal application name generated by Dokploy.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"status": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Status of the most recent deployment.",
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{Create: true, Update: true}),
		},
	}
}

func (r *applicationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T.", req.ProviderData))
		return
	}
	r.client = c
}

// slugify turns an application name into a Docker-safe base name. Dokploy
// appends its own random suffix, so this only needs to be a valid prefix.
func slugify(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ' || r == '_' || r == '-':
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		out = "app"
	}
	return out
}

// optionalString returns a pointer to the string value, or nil when the
// attribute is null/unknown/empty — used for API fields that must serialize as
// JSON null when unset.
func optionalString(v types.String) *string {
	if v.IsNull() || v.IsUnknown() || v.ValueString() == "" {
		return nil
	}
	s := v.ValueString()
	return &s
}

// configureAndDeploy applies docker provider config + env, triggers a deploy,
// and waits for it to finish. Used by both Create and Update.
func (r *applicationResource) configureAndDeploy(ctx context.Context, m *applicationModel, timeout time.Duration) error {
	id := m.ID.ValueString()

	if err := r.client.SaveDockerProvider(ctx, client.DockerProviderInput{
		ApplicationID: id,
		DockerImage:   m.DockerImage.ValueString(),
		RegistryURL:   m.RegistryURL.ValueString(),
		Username:      optionalString(m.RegistryUsername),
		Password:      optionalString(m.RegistryPassword),
	}); err != nil {
		return fmt.Errorf("saving docker provider: %w", err)
	}

	envStr, err := envMapToString(ctx, m.Env)
	if err != nil {
		return err
	}
	if err := r.client.SaveEnvironment(ctx, id, envStr); err != nil {
		return fmt.Errorf("saving environment: %w", err)
	}

	if err := r.client.Deploy(ctx, id); err != nil {
		return fmt.Errorf("triggering deploy: %w", err)
	}

	deployCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	return r.client.WaitForDeployment(deployCtx, id, deployPollInterval)
}

func (r *applicationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan applicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := plan.Timeouts.Create(ctx, defaultDeployTimeout)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	app, err := r.client.CreateApplication(ctx, client.ApplicationInput{
		Name:          plan.Name.ValueString(),
		AppName:       slugify(plan.Name.ValueString()),
		Description:   plan.Description.ValueString(),
		EnvironmentID: plan.EnvironmentID.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Error creating application", err.Error())
		return
	}
	plan.ID = types.StringValue(app.ID)
	plan.AppName = types.StringValue(app.AppName)

	if err := r.configureAndDeploy(ctx, &plan, createTimeout); err != nil {
		// The application exists; persist its id so a later apply can retry.
		plan.Status = types.StringValue("error")
		resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
		resp.Diagnostics.AddError("Application deploy failed", err.Error())
		return
	}

	plan.Status = types.StringValue("done")
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *applicationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state applicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	app, err := r.client.GetApplication(ctx, state.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading application", err.Error())
		return
	}

	state.Name = types.StringValue(app.Name)
	state.EnvironmentID = types.StringValue(app.EnvironmentID)
	state.DockerImage = types.StringValue(app.DockerImage)
	state.AppName = types.StringValue(app.AppName)
	state.Status = types.StringValue(app.ApplicationStatus)
	if app.Description != "" || !state.Description.IsNull() {
		state.Description = types.StringValue(app.Description)
	}
	if app.RegistryURL != "" || !state.RegistryURL.IsNull() {
		state.RegistryURL = types.StringValue(app.RegistryURL)
	}
	if app.Username != "" || !state.RegistryUsername.IsNull() {
		state.RegistryUsername = types.StringValue(app.Username)
	}
	// registry_password is intentionally NOT updated: the API does not return it.
	// Always populate env from the API so import works correctly.
	if app.Env != "" {
		envMap, diags := types.MapValueFrom(ctx, types.StringType, client.DotenvToMap(app.Env))
		resp.Diagnostics.Append(diags...)
		if !diags.HasError() {
			state.Env = envMap
		}
	} else if !state.Env.IsNull() {
		state.Env = types.MapValueMust(types.StringType, map[string]attr.Value{})
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *applicationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan applicationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := plan.Timeouts.Update(ctx, defaultDeployTimeout)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.client.UpdateApplication(ctx, plan.ID.ValueString(), client.ApplicationInput{
		Name:        plan.Name.ValueString(),
		Description: plan.Description.ValueString(),
	}); err != nil {
		resp.Diagnostics.AddError("Error updating application", err.Error())
		return
	}

	if err := r.configureAndDeploy(ctx, &plan, updateTimeout); err != nil {
		plan.Status = types.StringValue("error")
		resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
		resp.Diagnostics.AddError("Application deploy failed", err.Error())
		return
	}

	plan.Status = types.StringValue("done")
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *applicationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state applicationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteApplication(ctx, state.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Error deleting application", err.Error())
	}
}

func (r *applicationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
