package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/lucasaarch/terraform-provider-dokploy/internal/client"
)

var (
	_ resource.Resource                = &composeResource{}
	_ resource.ResourceWithConfigure   = &composeResource{}
	_ resource.ResourceWithImportState = &composeResource{}
)

type composeResource struct{ client *client.Client }

func NewComposeResource() resource.Resource { return &composeResource{} }

type composeModel struct {
	ID            types.String   `tfsdk:"id"`
	EnvironmentID types.String   `tfsdk:"environment_id"`
	Name          types.String   `tfsdk:"name"`
	Description   types.String   `tfsdk:"description"`
	ComposeFile   types.String   `tfsdk:"compose_file"`
	SourceType    types.String   `tfsdk:"source_type"`
	Env           types.Map      `tfsdk:"env"`
	ServerID      types.String   `tfsdk:"server_id"`
	AppName       types.String   `tfsdk:"app_name"`
	Status        types.String   `tfsdk:"status"`
	Timeouts      timeouts.Value `tfsdk:"timeouts"`
}

func (r *composeResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_compose"
}

func (r *composeResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "A Docker Compose stack managed by Dokploy. v0.5 supports source_type \"raw\" only (paste the YAML inline).",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"environment_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Environment that owns the stack. Changing forces replacement.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name":         schema.StringAttribute{Required: true, MarkdownDescription: "Display name."},
			"description":  schema.StringAttribute{Optional: true, MarkdownDescription: "Description. Once set, removing this attribute does not clear it on the server."},
			"compose_file": schema.StringAttribute{Required: true, MarkdownDescription: "Contents of the docker-compose.yml file."},
			"source_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("raw"),
				MarkdownDescription: "Source type. v0.5 only supports `raw` (inline YAML).",
			},
			"env": schema.MapAttribute{Optional: true, ElementType: types.StringType, MarkdownDescription: "Env vars passed to the stack."},
			"server_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Managed server ID. Omit to run on the Dokploy host. Changing forces replacement.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()},
			},
			"app_name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Internal name generated by Dokploy.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"status": schema.StringAttribute{Computed: true, MarkdownDescription: "Status of the most recent deploy."},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{Create: true, Update: true}),
		},
	}
}

func (r *composeResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client.Client, got %T.", req.ProviderData))
		return
	}
	r.client = c
}

func (r *composeResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan composeModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	createTimeout, diags := plan.Timeouts.Create(ctx, defaultDatabaseTimeout)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	envStr, err := envMapToString(ctx, plan.Env)
	if err != nil {
		resp.Diagnostics.AddError("Error reading env", err.Error())
		return
	}

	co, err := r.client.CreateCompose(ctx, client.ComposeInput{
		Name:          plan.Name.ValueString(),
		AppName:       slugify(plan.Name.ValueString()),
		Description:   plan.Description.ValueString(),
		EnvironmentID: plan.EnvironmentID.ValueString(),
		ServerID:      optionalString(plan.ServerID),
	})
	if err != nil {
		resp.Diagnostics.AddError("Error creating compose", err.Error())
		return
	}
	plan.ID = types.StringValue(co.ID)
	plan.AppName = types.StringValue(co.AppName)
	if co.ServerID != nil {
		plan.ServerID = types.StringValue(*co.ServerID)
	} else if plan.ServerID.IsUnknown() {
		plan.ServerID = types.StringNull()
	}

	// Apply compose_file / env / sourceType via update (default sourceType is "github").
	if err := r.client.UpdateCompose(ctx, co.ID, client.ComposeInput{
		SourceType:  "raw",
		ComposeFile: plan.ComposeFile.ValueString(),
		Env:         envStr,
	}); err != nil {
		resp.Diagnostics.AddError("Error saving compose configuration", err.Error())
		return
	}

	deployFn := func(ctx context.Context) error { return r.client.DeployCompose(ctx, co.ID) }
	statusFn := func(ctx context.Context) (string, error) {
		got, err := r.client.GetCompose(ctx, co.ID)
		if err != nil {
			return "", err
		}
		return got.ComposeStatus, nil
	}
	if err := deployAndWait(ctx, deployFn, statusFn, databasePollInterval, createTimeout); err != nil {
		plan.Status = types.StringValue("error")
		resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
		resp.Diagnostics.AddError("Compose deploy failed", err.Error())
		return
	}
	plan.Status = types.StringValue("done")
	plan.SourceType = types.StringValue("raw")
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *composeResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state composeModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	co, err := r.client.GetCompose(ctx, state.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading compose", err.Error())
		return
	}
	state.Name = types.StringValue(co.Name)
	state.EnvironmentID = types.StringValue(co.EnvironmentID)
	state.AppName = types.StringValue(co.AppName)
	state.Status = types.StringValue(co.ComposeStatus)
	state.ComposeFile = types.StringValue(co.ComposeFile)
	state.SourceType = types.StringValue(co.SourceType)
	if co.Description != "" || !state.Description.IsNull() {
		state.Description = types.StringValue(co.Description)
	}
	if co.ServerID != nil {
		state.ServerID = types.StringValue(*co.ServerID)
	} else {
		state.ServerID = types.StringNull()
	}
	if co.Env != "" {
		envMap, diags := types.MapValueFrom(ctx, types.StringType, client.DotenvToMap(co.Env))
		resp.Diagnostics.Append(diags...)
		if !diags.HasError() {
			state.Env = envMap
		}
	} else if !state.Env.IsNull() {
		state.Env = types.MapValueMust(types.StringType, map[string]attr.Value{})
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *composeResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan composeModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	updateTimeout, diags := plan.Timeouts.Update(ctx, defaultDatabaseTimeout)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	envStr, err := envMapToString(ctx, plan.Env)
	if err != nil {
		resp.Diagnostics.AddError("Error reading env", err.Error())
		return
	}
	if err := r.client.UpdateCompose(ctx, plan.ID.ValueString(), client.ComposeInput{
		Name:        plan.Name.ValueString(),
		Description: plan.Description.ValueString(),
		SourceType:  plan.SourceType.ValueString(),
		ComposeFile: plan.ComposeFile.ValueString(),
		Env:         envStr,
	}); err != nil {
		resp.Diagnostics.AddError("Error updating compose", err.Error())
		return
	}

	deployFn := func(ctx context.Context) error { return r.client.DeployCompose(ctx, plan.ID.ValueString()) }
	statusFn := func(ctx context.Context) (string, error) {
		got, err := r.client.GetCompose(ctx, plan.ID.ValueString())
		if err != nil {
			return "", err
		}
		return got.ComposeStatus, nil
	}
	if err := deployAndWait(ctx, deployFn, statusFn, databasePollInterval, updateTimeout); err != nil {
		plan.Status = types.StringValue("error")
		resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
		resp.Diagnostics.AddError("Compose deploy failed", err.Error())
		return
	}
	plan.Status = types.StringValue("done")
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *composeResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state composeModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteCompose(ctx, state.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Error deleting compose", err.Error())
	}
}

func (r *composeResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
