package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/lucasaarch/terraform-provider-dokploy/internal/client"
)

var (
	_ resource.Resource                = &hostScheduleResource{}
	_ resource.ResourceWithConfigure   = &hostScheduleResource{}
	_ resource.ResourceWithImportState = &hostScheduleResource{}
)

type hostScheduleResource struct {
	client *client.Client
}

func NewHostScheduleResource() resource.Resource { return &hostScheduleResource{} }

type hostScheduleModel struct {
	ID             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	CronExpression types.String `tfsdk:"cron_expression"`
	Command        types.String `tfsdk:"command"`
	ShellType      types.String `tfsdk:"shell_type"`
	Enabled        types.Bool   `tfsdk:"enabled"`
	Timezone       types.String `tfsdk:"timezone"`
	AppName        types.String `tfsdk:"app_name"`
}

func (r *hostScheduleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_host_schedule"
}

func (r *hostScheduleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "A cron-scheduled command run on the Dokploy host (the machine running Dokploy itself). Use this for instance-wide jobs.",
		Attributes: map[string]schema.Attribute{
			"id":              schema.StringAttribute{Computed: true, PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"name":            schema.StringAttribute{Required: true, MarkdownDescription: "Display name."},
			"cron_expression": schema.StringAttribute{Required: true, MarkdownDescription: "Cron expression."},
			"command":         schema.StringAttribute{Required: true, MarkdownDescription: "Shell command to run."},
			"shell_type":      schema.StringAttribute{Optional: true, Computed: true, MarkdownDescription: "Shell. Defaults to `bash`.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"enabled":         schema.BoolAttribute{Optional: true, Computed: true, MarkdownDescription: "Whether the schedule is active. Defaults to `true`."},
			"timezone":        schema.StringAttribute{Optional: true, MarkdownDescription: "IANA timezone."},
			"app_name":        schema.StringAttribute{Computed: true, MarkdownDescription: "Internal name generated by Dokploy.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
		},
	}
}

func (r *hostScheduleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client.Client, got %T.", req.ProviderData))
		return
	}
	r.client = c
}

func (m hostScheduleModel) toInput() client.ScheduleInput {
	in := client.ScheduleInput{
		Name:           m.Name.ValueString(),
		CronExpression: m.CronExpression.ValueString(),
		Command:        m.Command.ValueString(),
		ScheduleType:   "dokploy-server",
		ShellType:      m.ShellType.ValueString(),
		Timezone:       m.Timezone.ValueString(),
	}
	if !m.Enabled.IsNull() && !m.Enabled.IsUnknown() {
		v := m.Enabled.ValueBool()
		in.Enabled = &v
	}
	return in
}

func (r *hostScheduleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan hostScheduleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	s, err := r.client.CreateSchedule(ctx, plan.toInput())
	if err != nil {
		resp.Diagnostics.AddError("Error creating host schedule", err.Error())
		return
	}
	plan.ID = types.StringValue(s.ID)
	plan.AppName = types.StringValue(s.AppName)
	plan.ShellType = types.StringValue(s.ShellType)
	plan.Enabled = types.BoolValue(s.Enabled)
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *hostScheduleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state hostScheduleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	s, err := r.client.GetSchedule(ctx, state.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading schedule", err.Error())
		return
	}
	state.Name = types.StringValue(s.Name)
	state.CronExpression = types.StringValue(s.CronExpression)
	state.Command = types.StringValue(s.Command)
	state.ShellType = types.StringValue(s.ShellType)
	state.Enabled = types.BoolValue(s.Enabled)
	if s.Timezone != "" || !state.Timezone.IsNull() {
		state.Timezone = types.StringValue(s.Timezone)
	}
	state.AppName = types.StringValue(s.AppName)
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *hostScheduleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan hostScheduleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.UpdateSchedule(ctx, plan.ID.ValueString(), plan.toInput()); err != nil {
		resp.Diagnostics.AddError("Error updating host schedule", err.Error())
		return
	}
	// Re-read to populate computed fields after update.
	s, err := r.client.GetSchedule(ctx, plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading schedule after update", err.Error())
		return
	}
	plan.ShellType = types.StringValue(s.ShellType)
	plan.Enabled = types.BoolValue(s.Enabled)
	plan.AppName = types.StringValue(s.AppName)
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *hostScheduleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state hostScheduleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteSchedule(ctx, state.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Error deleting schedule", err.Error())
	}
}

func (r *hostScheduleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
